FROM keymetrics/pm2:12-alpine

WORKDIR /hive-jarvis
COPY package*.json yarn.* ecosystem.config.js ./

# Fix for 'could not get uid/gid'
RUN npm config set unsafe-perm true

RUN yarn

RUN yarn global add pm2

COPY . /hive-jarvis

# Show current folders
RUN ls

CMD [ "pm2-runtime", "start", "ecosystem.config.js", "--env", "production" ]